workflows:
  android-release:
    name: Android Release APK
    environment:
      flutter: stable

    scripts:
      - name: Generate missing platform folders
        script: |
          flutter create .
          flutter pub get

      - name: Run tests
        script: |
          flutter test

      - name: Build release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
